version: '3'
services:
  pgdatabase:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER:"root"
      - POSTGRES_PASSWORD:"root"
      - POSTGRES_DB:"ny_taxi"
    volumes:
      - "./ny_taxi_postgres_data:/var/lib/postgresql/data:rw"
    ports:
      - "5432:5432"
  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=root
    restart: always
    ports:
      - "8080:80"
    depends_on:
      - "pgdatabase"
    volumes:
      - pg_admin_data:/var/lib/pgadmin
volumes:
  pg_admin_data:
  ny_taxi_postgres_data:
